-- Run this in Supabase SQL Editor before deploying the coupon code.
-- Amounts use the same SYP integer values as products/orders.

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null,
  discount_percent numeric(5,2) not null check (discount_percent > 0 and discount_percent <= 100),
  maximum_discount numeric(14,2) null check (maximum_discount is null or maximum_discount > 0),
  minimum_order_amount numeric(14,2) not null default 0 check (minimum_order_amount >= 0),
  is_active boolean not null default true,
  starts_at timestamptz null,
  expires_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint coupons_code_uppercase check (code = upper(code)),
  constraint coupons_dates_valid check (expires_at is null or starts_at is null or expires_at > starts_at)
);

create unique index if not exists coupons_code_unique on public.coupons (code);

alter table public.orders
  add column if not exists coupon_code text null,
  add column if not exists discount_amount numeric(14,2) not null default 0,
  add column if not exists products_subtotal numeric(14,2) null;

-- Do not expose coupons to anonymous/authenticated storefront clients. The
-- checkout API uses the service-role client; admin access must be granted by
-- your existing staff-only RLS model.
alter table public.coupons enable row level security;

-- Replace "authenticated" with your existing admin role/policy if needed.
-- Example policy (only if your dashboard uses authenticated Supabase admins):
-- create policy "staff manage coupons" on public.coupons for all to authenticated
-- using (is_admin()) with check (is_admin());
