-- Run this AFTER 4-coupons-migration.sql.
-- It adds the usage rule and makes "one use per customer" safe even if two
-- checkout requests arrive at exactly the same time.

alter table public.coupons
  add column if not exists one_use_per_customer boolean not null default false;

alter table public.orders
  add column if not exists customer_profile_id bigint null;

create table if not exists public.coupon_usages (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.coupons(id) on delete cascade,
  profile_id bigint not null,
  idempotency_key text not null,
  used_at timestamptz not null default now(),
  unique (coupon_id, profile_id)
);

create index if not exists coupon_usages_profile_id_idx
  on public.coupon_usages (profile_id);

alter table public.coupon_usages enable row level security;

-- The checkout server uses the service-role client. Do not add a public
-- policy for this table; customers must not be able to create or remove uses.

-- This wraps the existing create_order_atomic RPC. A failed order rolls back
-- the coupon usage too, so a customer does not lose a one-time coupon.
create or replace function public.create_order_with_coupon_atomic(
  p_order jsonb,
  p_items jsonb,
  p_idempotency_key text,
  p_coupon_code text default null,
  p_discount_amount numeric default 0,
  p_products_subtotal numeric default null,
  p_customer_profile_id bigint default null
)
returns table (id bigint, total_price numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_coupon_id bigint;
  v_one_use_per_customer boolean := false;
  v_usage_id bigint;
  v_order record;
begin
  if p_coupon_code is not null and btrim(p_coupon_code) <> '' then
    select c.id, c.one_use_per_customer
      into v_coupon_id, v_one_use_per_customer
      from public.coupons c
      where c.code = upper(btrim(p_coupon_code))
        and c.is_active = true;

    if v_coupon_id is null then
      raise exception 'Coupon is no longer available';
    end if;

    if v_one_use_per_customer then
      if p_customer_profile_id is null then
        raise exception 'Customer profile is required for this coupon';
      end if;

      -- Same idempotency key is allowed for a retry; a different order is not.
      insert into public.coupon_usages (
        coupon_id, profile_id, idempotency_key
      ) values (
        v_coupon_id, p_customer_profile_id, p_idempotency_key
      )
      on conflict (coupon_id, profile_id) do update
        set idempotency_key = public.coupon_usages.idempotency_key
        where public.coupon_usages.idempotency_key = excluded.idempotency_key
      returning id into v_usage_id;

      if v_usage_id is null then
        raise exception 'This coupon has already been used on your account';
      end if;
    end if;
  end if;

  select * into v_order
    from public.create_order_atomic(
      p_order,
      p_items,
      p_idempotency_key
    )
    limit 1;

  if not found or v_order.id is null then
    raise exception 'Order was not created';
  end if;

  update public.orders
    set customer_profile_id = coalesce(
          public.orders.customer_profile_id,
          p_customer_profile_id
        ),
        coupon_code = case
          when p_coupon_code is null or btrim(p_coupon_code) = ''
            then public.orders.coupon_code
          else upper(btrim(p_coupon_code))
        end,
        discount_amount = case
          when p_coupon_code is null or btrim(p_coupon_code) = ''
            then public.orders.discount_amount
          else greatest(0, coalesce(p_discount_amount, 0))
        end,
        products_subtotal = case
          when p_coupon_code is null or btrim(p_coupon_code) = ''
            then public.orders.products_subtotal
          else greatest(0, coalesce(p_products_subtotal, 0))
        end
    where public.orders.id = v_order.id;

  return query
    select v_order.id::bigint, v_order.total_price::numeric;
end;
$$;

revoke all on function public.create_order_with_coupon_atomic(
  jsonb, jsonb, text, text, numeric, numeric, bigint
) from public;

